spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testBD
    username: "postgres"
    password: "admin"
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080