spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${USER_NAME}
    password: ${PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true