spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
  output:
    ansi:
      enabled: always

server:
  address: 0.0.0.0
  port: ${PORT:8080}

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  dsn: "https://8c2f2ed2925251ca7f8f37644e968dce@o4507531613241344.ingest.us.sentry.io/4507531629101056"
  tracesSampleRate: 1.0
  exception-resolver-order: -2147483647

