spring:
  datasource:
    url: jdbc:h2:mem:project
    username: "admin"
    password: "123"
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true